version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: dev-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ctracker
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: dev-adminer
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  postgres-data:
