version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - stack.env
    ports:
      - '3333:3333'
    networks:
      - nginx_proxy_default

networks:
  nginx_proxy_default:
    external: true
  
