version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - '3333:3333'
    networks:
      - nginx_proxy_default

networks:
  nginx_proxy_default:
    external: true
  
